### ISSUE TITLE
System did not display file size

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#10]
**Description:**
The system fails to display the file size. This absence of file size can hinder users' ability to assess the suitability of the files for their needs, leading to potential inefficiencies. To enhance user experience and facilitate informed decision-making, it is imperative for the system to include the file size alongside file metadata.

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button
click on "Tr Text" button

**Expected result:**
The system should display supported file size

**Actual result:**
The system did not displayed file size 

**Pictures:**
![Screenshot from 2024-03-05 15-40-00](https://github.com/xiarahman/eda-ai/assets/109179391/f705dab7-2f0b-4bc4-977e-6e4db3bf0be9)

**Comment by xrasad** [comment]
@Tehreem-personal could you please verify the issue, thanks

**Comment by Tehreem-personal** [comment]
Fixed in latest push

**Comment by xrasad** [comment]
i will discus it to mubashir bhai then i will update the ticket
