### ISSUE TITLE
LLama is integrated and should be handled from FE 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#101]
**Description:**
llama 2 7b model is now integrated, llama is analyses overall content and gives result of overall content not on sentence by sentence and the emotion that detects are ["angry", "disgust","fear","happy","sad","surprise","neutral"]. For API details please coordinate with Alamgir from BE.

**Priority:** p1

**Expected result:**
It should handled as soon as possible from UI-UX and FE and kindly before implementing do consult with management.

**Comment by xrasad** [comment]
@shandev18 @devarsalanali @Tehreem-personal  kindly verify the ticket

**Comment by Tehreem-personal** [comment]
Fixed in latest code. the api end point from front end has been changed

**Comment by xrasad** [comment]
I'll waiting for merging once merge and retest then i will close it

**Comment by Tehreem-personal** [comment]
Llama end-point integration is merged. Kindly re-test..

**Comment by Tehreem-personal** [comment]
@shandev18 for UI changes we have another ticket. You will be working on that.. This ticket of mine is already merged in main. Let asad test the api-endpoint and close this one
