### ISSUE TITLE
Implement Lables for llama on UI and update UI according to new changes 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#107]
Description:
Update UI according to new changes as specified in Figma design I.e icon, content beneath result label etc 

Severity: s3
Priority: p1

Expected result:
Changes should be  reflect over text module and audio to text section in video module 
Actual result:
It is not yet implementing

**Comment by xrasad** [comment]
@shandev18

**Comment by shandev18** [comment]
issue fixed in EDA-107
