### ISSUE TITLE
Bulk video uploads are not supported through either the "Drag" option or the standard "Upload" method.

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#13]
**Description:**
Upload feature currently does not support bulk video uploads using either the "Drag" option or the standard "Upload" method

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag multiple videos or click on "upload" button

**Expected result:**
The system should support bulk video upload

**Actual result:**
bulk video uploading currently not supporting

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
this feature only supports one video to upload and user cannot upload bulk videos 
and description is also updated

**Comment by xrasad** [comment]
issue fixed thanks
