### ISSUE TITLE
"video upload" module, drag option not supported for some videos format except ".mov & .vob" on local server but on main peshawar server some times it support "Drag" option and some time it stuck.

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#14]
**Description:**
The "Drag" option is currently not supported on our local server, and while it is available on the main Peshawar server, it intermittently experiences functionality issues, causing occasional delays or getting stuck.

**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag different format videos

**Expected result:**
The Drag option should properly on local and main server

**Actual result:**
The Drag option currently not working and stuck sometime on main server

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
working fine on my end
