### ISSUE TITLE
Dragging one video for processing, if failed, prevents subsequent video drags.

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#16]
**Description:**
If one video fails to process after dragging it, subsequent video drags will be prevented

**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag videos

**Expected result:**
The system should allow video when one proccess is failed

**Actual result:**
The system did not allow video when one proccess is failed

**Picture:**
![Screenshot from 2024-03-07 12-27-07](https://github.com/xiarahman/eda-ai/assets/109179391/582dffda-401c-4f6d-9a10-bd6a6be62313)

**Comment by shandev18** [comment]
working fine on my end
