### ISSUE TITLE
on home page header should be sticky 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#17]

**Comment by xrasad** [comment]
@shandev18 could you please check the issue

**Comment by Tehreem-personal** [comment]
I have fixed in latest push

**Comment by xrasad** [comment]
tehreem i have pull the changes the header is sticky now but when i click on "how it works" it redirect to that section but title is hide behind header and then i click on  "home" on header the home-page did not refresh

**Comment by Tehreem-personal** [comment]
i have fixed in the latest code. Please verify

**Comment by Tehreem-personal** [comment]
I have fixed

**Comment by xrasad** [comment]
issue is fixed thanks
