### ISSUE TITLE
footer overlaps when more text  extracted on sentiments 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#19]
**Description:**
When more text is extracted for sentiment analysis, the footer overlaps, leading to a disruption in the display. This issue affects the user experience, as it obstructs the readability of the content and may cause confusion. A resolution is necessary to ensure seamless viewing of sentiment analysis results.

**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
click on Analyze video 
upload video

**Expected result:**
The system should not overlap footer when more text extracted

**Actual result:**
Footer overlap

**Picture:**
![Screenshot from 2024-03-12 02-43-19](https://github.com/xiarahman/eda-ai/assets/109179391/08dade69-53e7-4e9b-bb38-2a129ab46a8c)

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
above mentioned issue is fixed, kindly retest .... Thanks

**Comment by xrasad** [comment]
issue fixed thank you
