### ISSUE TITLE
The "Load More" option should not be displayed when all text has been displayed.

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#20]
**Description:**
The "Load More" option should disappear once all the text has been displayed.

**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Click on analyze button
upload video 

**Expected result:**
The system should not display "load more" option 

**Actual result:**
load more option still visible

**Picture:**
![Screenshot from 2024-03-12 11-24-05](https://github.com/xiarahman/eda-ai/assets/109179391/26e77ae9-cac4-4799-a8a4-e381880b2a94)

**Comment by shandev18** [comment]
Above mentioned issue is fixed, kindly retest .... Thanks

**Comment by xrasad** [comment]
Back button and sentence title hide when you scroll down @shandev18 please verify the issue

**Comment by shandev18** [comment]
The issue has been resolved, and now only the sentences are scrollable.

**Comment by xrasad** [comment]
thanks issue resolved
