### ISSUE TITLE
The "upload video, Webcam, Tr Text" modules text are changed 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#21]
**Description:**
The text in the "Upload Video," "Webcam," and "Text" modules changes upon returning to the analyze page from the result page, causing inconsistency in the user interface

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
upload video and return back to the analyze page 

**Expected result:**
Text of module should not be changed 

**Actual result:**
Text is changed 

**Picture:**
![Screenshot from 2024-03-11 23-02-05](https://github.com/xiarahman/eda-ai/assets/109179391/6d84bdb4-acd0-44e5-aa2e-aa7f70bd5897)

**Comment by shandev18** [comment]
issue resolved

**Comment by xrasad** [comment]
thanks issued fixed
