### ISSUE TITLE
for a blur face with 720 p resolution video is playback but frames did not extract and no data shows on graphs

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#22]
**Description:**
Playback of a 720p resolution video for blurring faces is successful, but the frames fail to extract

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload video

**Expected result:**
The system should display frames 
 
**Actual result:**
The system did not display frames

**Picture:**
![Screenshot from 2024-03-12 11-20-46](https://github.com/xiarahman/eda-ai/assets/109179391/d69401ac-73b5-436f-afad-17ba3d910796)

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
Please assign this ticket to the backend team since frames originate from the backend, and video processing is also managed there.

**Comment by xrasad** [comment]
okay i will discus it with alamgir
