### ISSUE TITLE
 "Uncaught runtime errors"  displays when navigated to previous page

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#23]
**Description:**
Navigating to the previous page while a task is processing, or even without initiating any processing, triggers "Uncaught runtime errors" within the system, indicating a flaw in error handling during navigation transitions

**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload  videos 
go back to previous page from result page 

**Expected result:**
The system should redirect to the expected page

**Actual result:**
Uncaught runtime error message displayed

**Picture:**
![Screenshot from 2024-03-11 22-32-51](https://github.com/xiarahman/eda-ai/assets/109179391/1efb48e5-bbab-4b41-9e7b-f7b0f9fc2e8d)

**Comment by xrasad** [comment]
@Tehreem-personal could you please verify the issue

**Comment by Tehreem-personal** [comment]
fixed in latest code. Please check

**Comment by xrasad** [comment]
issue fixed thank you
