### ISSUE TITLE
The system fails to prevent multiple video uploads simultaneously 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#24]
**Description:**
The system lacks the capability to prevent users from uploading multiple videos simultaneously. This oversight may result in system overload, data inconsistencies, or other unintended consequences. Implementing a mechanism to restrict simultaneous uploads can help maintain system stability and data integrity

**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload  videos

**Expected result:**
The system should not support simultaneous upload

**Actual result:**
The system currently allow simultaneous upload 

**Picture:**
![Screenshot from 2024-03-14 10-55-26](https://github.com/xiarahman/eda-ai/assets/109179391/89493b9c-8dff-4ed1-8577-b5c803292080)

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
Above mentioned issue is fixed, kindly retest .... Thanks

**Comment by xrasad** [comment]
issue fixed
