### ISSUE TITLE
percentage label on emotion pi-chart start flickering when mouse is hover

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#25]
**Description:**
On the result page of " Text, upload video, Live stream"  As you hover your mouse over the emotion pie chart, you'll notice the percentage labels start to flicker 

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Enter text in the text of Tr Text module
hover your mouse cursor over pi-chart percentage label 

**Expected result:**
The label should be stable and still

**Actual result:**
The do flickering when mouse cursor hover

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
Above mentioned issue is fixed, kindly retest .... Thanks

**Comment by xrasad** [comment]
issue fixed

**Comment by xrasad** [comment]
@shandev18 please verify the issue it occurred again.

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
issue resolved

**Comment by xrasad** [comment]
@shandev18 @Tehreem-personal over all modules have same issue occurred again on "top emotion" cart

**Comment by shandev18** [comment]
I already discussed this with sir Zia and added this issue to non-issue because there is no other solution for this
