### ISSUE TITLE
Invalid name displays of the Text module

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#26]
**Description:**
When attempting to access the Text module, an error appears, indicating "Invalid name." It is not same as in design.

**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page

**Expected result:**
The module name should be "Text"

**Actual result:**
The system displays invalid module name as "Tr Text"
**Picture:**
Invalid name as system display
![Screenshot from 2024-03-20 11-21-29](https://github.com/xiarahman/eda-ai/assets/109179391/4ae25d9a-f928-4a21-b2f5-edae83f7aaf3)
valid name in design is..
![Screenshot from 2024-03-20 11-23-42](https://github.com/xiarahman/eda-ai/assets/109179391/d085bd35-f78c-4acc-b4e0-e45a91335b97)

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
The library we are currently using has certain limitations, notably the absence of Ant Design icons in the UI. However, I will make the necessary changes to address this.

**Comment by shandev18** [comment]
issue fixed
