### ISSUE TITLE
Not able procceed request when larg text or paragraph to Text module

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#27]
**Description:**
When attempting to process a large text or paragraph, the Text module displays an error message indicating it cannot proceed with the request. This typically means the module has limitations on special charactors

**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
upload file or input large text

**Expected result:**
The system should successfully execute request

**Actual result:**
The system did not proceed request to analyze throw error

**Picture:**
![Screenshot from 2024-03-20 12-04-36](https://github.com/xiarahman/eda-ai/assets/109179391/2a064d42-b494-4b9b-a6b2-790bf3e1895a)

**Comment by xrasad** [comment]
@Tehreem-personal could you please verify the issue

**Comment by Tehreem-personal** [comment]
Fixed in latest code

**Comment by xrasad** [comment]
thank you tehreem
