### ISSUE TITLE
Detected frames are not changed by keyboard lift-right keys niether any option availabe through mouse to change it 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#28]
**Description:**
When using the "analyze_video" module, After video analyzation frames are detected but user unable to change the frames until unless he/she close frame and click on another frame. There should be a mechanism to easily user change frame with keyboard keys and mouse as well without closing the frame 

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload video

**Expected result:**
The system should allow user to change frames without any hindrance 

**Actual result:**
The system did not allowed user to change the picture 

**Picture**
![Screenshot from 2024-03-27 12-10-40](https://github.com/xiarahman/eda-ai/assets/109179391/fd316a2d-d8ff-4b4f-820a-9f62c7044bd5)

**Comment by xrasad** [comment]
@shandev18 @devarsalanali could you please verify the issue

**Comment by shandev18** [comment]
issue fixed
