### ISSUE TITLE
"contact us" on footer is not aligned 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#30]
![Screenshot from 2024-03-28 12-55-28](https://github.com/xiarahman/eda-ai/assets/109179391/36cfbfbc-edda-430f-9cb0-53ef40c2cb52)

**Comment by xrasad** [comment]
@shandev18 could you please look into it thanks

**Comment by Tehreem-personal** [comment]
I have fixed in latest code

**Comment by xrasad** [comment]
thanks issue is fixed
