### ISSUE TITLE
Yellow colour is not clearly visible in the graph of "Analyze_video" module result

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#31]
![Screenshot from 2024-03-28 13-31-48](https://github.com/xiarahman/eda-ai/assets/109179391/5bad1490-bd51-42d8-b18e-6220918baef8)

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
Above mentioned issue is fixed, kindly retest .... Thanks

**Comment by xrasad** [comment]
in which branch did push the changes

**Comment by shandev18** [comment]
optimization

**Comment by xrasad** [comment]
thanks issue fixed
