### ISSUE TITLE
Feature section carts on Home page, some part of it are hide when to click on "feature"

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#32]
![Screenshot from 2024-03-28 13-40-44](https://github.com/xiarahman/eda-ai/assets/109179391/14a2cfc3-2126-4a70-82d9-f6f75993f6da)

**Comment by xrasad** [comment]
@Tehreem-personal could you please verify the issue

**Comment by Tehreem-personal** [comment]
Fixed in latest push

**Comment by xrasad** [comment]
thanks issue is fixed
