### ISSUE TITLE
The given error message should display from frontend 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#33]
**Description:**
when you upload invalid video format the system should display given error message. The error message are fixed by BE.

**severity:** s3

**Priority**: p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag/upload invalid videos

**Expected result:**
The system should display error message from FE

**Actual result:**
The system did not error display error message 

**Picture:**
![Screenshot from 2024-04-01 10-49-41](https://github.com/xiarahman/eda-ai/assets/109179391/96458666-27fc-40ce-8051-af787a9698f9)

**Comment by shandev18** [comment]
![error msg](https://github.com/xiarahman/eda-ai/assets/133768718/9cc3cf49-53cf-4ed9-8c25-89ac2de21ae9)

now the error message will appear on FE when you upload invalid video format

**Comment by xrasad** [comment]
thanks issue fixed
