### ISSUE TITLE
On "Analyze_text" module the file supported statment misplaced.

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#34]
![Screenshot from 2024-04-01 13-18-58](https://github.com/xiarahman/eda-ai/assets/109179391/d792d845-a8c6-4330-9d0b-3c0f74a6a781)

**Comment by xrasad** [comment]
@Tehreem-personal could you please verify the issue

**Comment by Tehreem-personal** [comment]
Fixed in latest code.

**Comment by xrasad** [comment]
now the text are bold and color is too dark 
![Screenshot from 2024-04-03 16-21-42](https://github.com/xiarahman/eda-ai/assets/109179391/769367ea-a02b-4231-864d-2346df9f69e6)

**Comment by Tehreem-personal** [comment]
Code is updated according to latest figma design update. Please re-check that
