### ISSUE TITLE
"Analyze" page stuck when to upload video in "upload_video" module with no sound/audio

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#35]
**Description:**
when I upload videos with no audio as a result the "Analyze" page will stuck
**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag/upload videos

**Expected result:**
The system should display/detect correct emotion with no crash

**Actual result:**
The system crash when i upload video 

**Picture:**
![Screenshot from 2024-04-01 13-26-05](https://github.com/xiarahman/eda-ai/assets/109179391/ff2c0240-1660-4b8a-bf20-0d8477dc56de)

**Comment by xrasad** [comment]
@shandev18 could you please verify the issue

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
when i click on left or Right arrow at "images" section, when images finished or reached to 1st or last image the movement of images should stop and but it still move

**Comment by xrasad** [comment]
![Screenshot from 2024-04-03 16-16-04](https://github.com/xiarahman/eda-ai/assets/109179391/03af6fe8-c6f4-4f08-b9be-5b771bc6f047)

**Comment by shandev18** [comment]
This issue only occurs on localhost and not on the server. It arises due to a delay in fetching frames. The server efficiently caches frames, so there are no issues with most videos. However, this problem only arises when uploading a video locally.
