### ISSUE TITLE
frames are repeated in the "analyze_video" module

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#41]
**Description:**
I uploaded multiple videos same result have been shown, 41 frames displayed on website but 33 frames are detected in the API call when inspected the request call

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload video

**Expected result:**
The system should display exact frames what are detected by the system.

**Actual result:**
The system did not display exact frames what are detected by the system.

**Picture**
![Screenshot from 2024-04-18 15-20-56](https://github.com/xiarahman/eda-ai/assets/109179391/38ad1a09-41e9-412e-a1f1-77628409ed7b)
![Screenshot from 2024-04-18 15-23-57](https://github.com/xiarahman/eda-ai/assets/109179391/063a3add-8209-440b-8bc5-4af3e4bb925c)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by xrasad** [comment]
8 frames are repeated in every video

**Comment by shandev18** [comment]
fixed in the latest code

**Comment by xrasad** [comment]
issue fixed
