### ISSUE TITLE
Absent of colored box and thumbs-up sign in the analyze_video module preview section 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#42]
**Description:**
As per the figma-design there is no colored boxed that represent emotion with pie-chart and no thumbs-up sign in the sentiment and also the the text of "emotion & sentiment" are not dark black (bold). In the preview section on website sentences are separated by line but in figma design it is separated by like 3d shadow something.

**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
upload video

**Expected result:**
It should be matched with figma-design

**Actual result:**
colored box and thumbs up are not present on website

**Picture**
![Screenshot from 2024-04-19 14-35-02](https://github.com/xiarahman/eda-ai/assets/109179391/d2c696b6-635d-4c7e-ac0b-1b04e224f0de)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by Tehreem-personal** [comment]
Fixed

**Comment by xrasad** [comment]
fixed thanks
