### ISSUE TITLE
color square boxs are clickable, emotion and sentiment not aligned 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#46]
**Description:**
If user clicks on it, it moves downwards and then returns back to its actual position after few seconds. other than that emotion and sentiment in the preview section of text_module are not aligned 

**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
input text 

**Expected result:**
The color-boxs should not be clickable 

**Actual result:**
It is clickable 

**Picture:**
![image (1)](https://github.com/xiarahman/eda-ai/assets/109179391/830e52bd-64e4-4100-8fe6-da4d3bb3ffb1)

**Comment by xrasad** [comment]
@Tehreem-personal please verify the issue thanks

**Comment by Tehreem-personal** [comment]
Fixed. Please verify

**Comment by xrasad** [comment]
@Tehreem-personal  color-box is now un-clickable but emotion and sentiment are not aligned
