### ISSUE TITLE
Webcame module "start-stream" button should place down of the screen as per figma 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#50]
**application picture:**
![Screenshot from 2024-04-23 14-37-15](https://github.com/xiarahman/eda-ai/assets/109179391/837a1da3-c2d4-4a6a-bf6e-26498bc1c9bf)
**figma design:**
![Screenshot from 2024-04-23 14-43-51](https://github.com/xiarahman/eda-ai/assets/109179391/8df98aa8-6fdc-4d61-badd-d2d3cfe20456)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
fixed in the latest code

**Comment by xrasad** [comment]
As you see in the picture buttons are not aligned.
![Screenshot from 2024-04-29 11-39-15](https://github.com/xiarahman/eda-ai/assets/109179391/3d76f859-be70-4947-a7e3-e1a66489f639)

when you refresh the page both button are displaced from their expected location.
![Screenshot from 2024-04-29 11-46-01](https://github.com/xiarahman/eda-ai/assets/109179391/9aa733c8-ac62-47ae-b6d1-e43a1a8e604c)

**Comment by xrasad** [comment]
@shandev18 please verify the above issues thanks.

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
issue fixed
