### ISSUE TITLE
Text_module statement in the dialog box should be same as in figma design 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#51]
**On Application:**
![Screenshot from 2024-04-23 14-50-24](https://github.com/xiarahman/eda-ai/assets/109179391/92f694f7-3d01-4a0d-9c81-f29848f9e329)

**On Figma design:**
![Screenshot from 2024-04-23 14-50-39](https://github.com/xiarahman/eda-ai/assets/109179391/05aeba90-f214-4bbe-a661-7c64daccccff)

**Comment by shandev18** [comment]
issue fixed in the latest code

**Comment by xrasad** [comment]
As see the text size is small and result section is moved towards left side and also text break out from sentiment section.

![Screenshot from 2024-04-29 16-04-02](https://github.com/xiarahman/eda-ai/assets/109179391/492c1854-a469-4d0c-b43a-ed347e4652a7)

**Comment by xrasad** [comment]
@Tehreem-personal please verify the issue

**Comment by Tehreem-personal** [comment]
I have fixed this result screen according to the updated UI in latest code. Please check that

**Comment by xrasad** [comment]
issue fixed
