### ISSUE TITLE
Top three emotion text goes outside from cart (Alignment issue)

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#52]
**Description:**
In all module top three emotion text breaks and goes outside from cart on result page when screen resolution greater then 300% and it consistently appear over different device from console as well
**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload video/ input text/ live-stream

**Expected result:**
each and every text, heading in all section/carts should be aligned and do not break

**Actual result:**
top three emotion text goes outside from cart

**Picture**
![Screenshot from 2024-04-24 12-44-01](https://github.com/xiarahman/eda-ai/assets/109179391/be4bf5ad-fc3d-46a4-aa10-527cdbd7c51a)
![Screenshot from 2024-04-24 12-43-19](https://github.com/xiarahman/eda-ai/assets/109179391/7d5f5d55-b0d8-417a-b18a-8849369f2438)
![Screenshot from 2024-04-24 12-37-36](https://github.com/xiarahman/eda-ai/assets/109179391/07a639a1-d427-4bfb-9fc9-97518c6a4190)
![Screenshot from 2024-04-24 12-36-00](https://github.com/xiarahman/eda-ai/assets/109179391/32b195bf-2f08-45b3-98d6-f7e5c00e46e5)
![Screenshot from 2024-04-24 12-34-55](https://github.com/xiarahman/eda-ai/assets/109179391/64f5d4cf-3637-492a-bdd8-5ab21fd48c19)
![Screenshot from 2024-04-24 12-33-27](https://github.com/xiarahman/eda-ai/assets/109179391/b80dd9ae-f544-479a-be80-a464315eee91)
![Screenshot from 2024-04-24 12-30-27](https://github.com/xiarahman/eda-ai/assets/109179391/901128f9-1081-48cc-bef7-6ab4826181cd)
![Screenshot from 2024-04-24 12-26-19](https://github.com/xiarahman/eda-ai/assets/109179391/8c0f7fdc-1da8-4860-84f7-e16d001213fe)
![Screenshot from 2024-04-24 12-24-15](https://github.com/xiarahman/eda-ai/assets/109179391/f962ff60-a33e-4afa-9088-4724efc72818)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
issue fixed

**Comment by shandev18** [comment]
fixed in the latest code

**Comment by xrasad** [comment]
issue is fixed
