### ISSUE TITLE
The system allow multi "live-stream" over multiple browser in single Laptop

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#53]
**Description:**
when i start live stream over multiple browser it did not display any error message and recording was started, one live-stream i had stop earlier and other one was after some time as a result both have different result with same job_id and when i refresh the result page the result got changed to latest recording

**Severity:** 3

**priority:** 1

**Expected result:**
The system should not allow live-stream over multiple browser in a single laptop

**pictures**
![Screenshot from 2024-04-25 10-04-42](https://github.com/xiarahman/eda-ai/assets/109179391/5151c3ae-4073-419d-8eda-368d71178aaf)
![Screenshot from 2024-04-25 10-29-29](https://github.com/xiarahman/eda-ai/assets/109179391/8fc98dc2-fdcc-475c-ae74-d5781a7a1557)
![Screenshot from 2024-04-25 10-29-50](https://github.com/xiarahman/eda-ai/assets/109179391/7ae39eb8-cd8f-421e-8bcb-25def490e834)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
already in discussion we'll deal with this issue after completion of  login signup
