### ISSUE TITLE
Sentiment percentage roundoff values did not handled accuratly 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#54]
**Description:**
I entered a text, sentiment percentage values did not accurately displayed
**severity:** s3

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload video/ input text

**Expected result:**
It should acccurately roundoff and displayed 

**Actual result:**
Invalid values are displayed 

**Picture:**
![Screenshot from 2024-04-25 10-21-36](https://github.com/xiarahman/eda-ai/assets/109179391/f5f6bef6-b8fa-4844-997c-69845238756a)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by Tehreem-personal** [comment]
I have fixed this issue in latest code
