### ISSUE TITLE
Remove "images:" heading from frames/Pictures

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#55]
**Description:**
As per figma design there is no "images" heading on frames cart 
**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Drag or upload video

**Expected result:**
It should be as in figma design 

**Picture:**
![Screenshot from 2024-04-25 12-19-36](https://github.com/xiarahman/eda-ai/assets/109179391/dc08c7ca-e226-40e1-8b81-82f956e65dbe)
![Screenshot from 2024-04-25 12-19-19](https://github.com/xiarahman/eda-ai/assets/109179391/1041fe3e-5038-42d3-92f2-20126b839155)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
The heading of the image has been added based on the recommendation of Sir Salman Farooq in the meeting.
