### ISSUE TITLE
button & percentage bar in sentiment cart disappear when page is refresh

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#56]
**Description:**
I uploaded a video and when i refreshed the page button, percentage bar suddenly disappear & "Go back" button partially hide in frames cart
 
**severity:** s1

**Priority:** p1

Execution steps:
Go to eae web application
click on "try now" button on home page
Drag or upload video

**Expected result:**
The page should be stable when refresh 

**Actual result:**
button and percentage bar disappear 

**Picture:**
![Screenshot from 2024-04-25 12-20-04](https://github.com/xiarahman/eda-ai/assets/109179391/8abaef34-f51d-48f2-8416-10f2eef018ba)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by Tehreem-personal** [comment]
i have fixed  in latest code.

**Comment by xrasad** [comment]
issue fixed
