### ISSUE TITLE
graph cart loss alingement when page is refresh

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#57]
**Description:**
i started the live stream and viewed the result when i refreshed the page the graph losses its alignment
 
**severity:** s1

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button on home page
Start live stream 

**Expected result:**
The page should stable 

**Actual result:**
graph cart is not aligned

**Picture:**
![Screenshot from 2024-04-25 15-36-13](https://github.com/xiarahman/eda-ai/assets/109179391/a1950d21-ef5a-4ee3-b0bf-73a0eef6e336)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by Tehreem-personal** [comment]
i have fixed all the alignment issues already occuring  on page refresh in latest code.

**Comment by xrasad** [comment]
issue fixed thanks
