### ISSUE TITLE
Two person start live-stream , one person live-stream screen shows on 2nd person pc/laptop

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#58]
Description:
when i started live-stream on server and after some second another person also start live-stream on same server the first 1st person screen displayed on 2nd person screen. 2nd person captured pictures will displayed 1st person API call confirmed from browser inspection. from backend both have unique job_ids but on frontend both have same job_ids assigned 

severity: s1

Priority: p1

Execution steps:
Go to eae web application
click on "try now" button on home page
start live-stream

Expected result:
Each live stream should have separate live-stream with unique job_ids 

Actual result:
one person live-stream screen shows on 2nd person pc/laptop

**Comment by alamgiruk7** [comment]
@xrasad @shandev18 , I have resolved this issue from backend. No work required from frontend as of now. Thanks

**Comment by shandev18** [comment]
@alamgiruk7 ok thanks
