### ISSUE TITLE
Improper home-page display when to click on "home" button or "main-logo"

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#59]
severity : s3
priority : p1
picture :
![Screenshot from 2024-05-03 11-33-38](https://github.com/xiarahman/eda-ai/assets/109179391/8de2b84f-4be7-4338-945f-380767d226b2)

**Comment by xrasad** [comment]
@Tehreem-personal @shandev18 verify the issue

**Comment by Tehreem-personal** [comment]
Fixed in latest code

**Comment by xrasad** [comment]
issue resolved
