### ISSUE TITLE
Failure to Handle Special Characters and symbols in the text module and system execute request 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#6]
**Description:**
When attempting to process input text containing special characters and symbols within the text module, the system encountered a failure, resulting in the execution of an erroneous request.

**severity: s1**

**Priority: p2**

**Execution steps:**
Go to eae web application 
click on "try now" button 
click on "Tr Text" button 
input invalid text containing special character and symbols 
submit the request

**Expected result:**
The system should display proper error message
**Actual result:**
The system execute the request successfully and generates proper result

**Comment by xrasad** [comment]
@Tehreem-personal Could you please verify the issue? Thank you.

**Comment by Tehreem-personal** [comment]
Fixed above mentioned error in latest code

**Comment by xrasad** [comment]
@Tehreem-personal thank you.
