### ISSUE TITLE
back button not aligned in all modules

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#60]
Severity: 3
Priority: 1
pictures:

upload video module 
![Screenshot from 2024-05-03 12-29-43](https://github.com/xiarahman/eda-ai/assets/109179391/19a57f20-aac1-4404-9068-af6008b8af06)

live stream module 
![Screenshot from 2024-05-03 12-28-21](https://github.com/xiarahman/eda-ai/assets/109179391/a7f3b412-f051-4498-8a41-c1fc946fdc05)

text module
![Screenshot from 2024-05-03 12-32-06](https://github.com/xiarahman/eda-ai/assets/109179391/e94a52ec-fc5c-4e32-97e6-e2c9fdb20dad)

figma design
![Screenshot from 2024-05-03 12-30-36](https://github.com/xiarahman/eda-ai/assets/109179391/5de72114-21cf-4795-889f-ccfdb90f8843)

**Comment by xrasad** [comment]
@shandev18 @Tehreem-personal

**Comment by shandev18** [comment]
fixed this issue in latest code

**Comment by xrasad** [comment]
issue fixed
