### ISSUE TITLE
Same Text is written in ‘Process Section’ and ‘Reports Section’ on Homepage 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#63]
**Description:** 
In report section and Process section the text is same 

**Steps:** 
Navigate to URL: http://cacf.ddns.net:8000  
Go to EDA web application 
Scroll down the page  
Observe the text written in “Process” and “Report” sections 

**Expected Result:** 
Proper and relevant text should appear in both sections 

**Actual Result:** 
Same text appears in both sections 

**Environment:** 
Test 

**Severity:** S2 

**Priority:** P2 

**Screen shot:**

![Screenshot from 2024-05-08 16-05-01](https://github.com/xiarahman/eda-ai/assets/109179391/1895b8ef-12c1-42a9-b6b7-3977567a9cd7)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
issue is fixed
