### ISSUE TITLE
Screen is not aligned from lift side in live-stream module 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#64]
**Description:**
In live-stream module the screen is not aligned from left side

**Steps:**
Navigate to URL:http://localhost:3000/analyze
Go to EDA web application
Go to live stream
Observe the screen from left side

**Expected Result:**
screen should be properly aligned 

**Actual Result:**
from left side screen is not aligned with above buttons

**Environment:**
Test

**Severity:** S1

**Priority:** P2

**Screen shot:**
![Screenshot from 2024-05-09 10-07-16](https://github.com/xiarahman/eda-ai/assets/109179391/c4a50997-41b5-43df-b650-4608d99ebcce)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
issue fixed in the latest code

**Comment by xrasad** [comment]
issue fixed
