### ISSUE TITLE
percentage values overflow from the chart on home page

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#65]
**Description:**
On home page when you scroll down to how it works the value of percentage is overflow from the pie-chart

**Steps:**
Navigate to URL:http://localhost:3000/analyze
Go to EDA web application
Go to live stream
Observe the screen from left side

**Expected Result:**
value should be properly fitted on the chart 

**Actual Result:**
percentage values overflow from the chart 

**Environment:**
Test

**Severity:** S3

**Priority:** P1

**Screen shot:**
![Screenshot from 2024-05-09 10-20-46](https://github.com/xiarahman/eda-ai/assets/109179391/ad5787a0-b675-4834-a744-cd052d398485)

**Comment by xrasad** [comment]
@shandev18please verify the issue

**Comment by Tehreem-personal** [comment]
@xrasad Please verify this issue from arsalan first because this is what we have got in our figma design.. here on the homepage this is simply an image imported from the figma.

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
issue fixed
