### ISSUE TITLE
Uploaded file did not removed if text is changed 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#66]
**Description:**
Upload text file, once text is displayed in the dialog box then select all text and write something 
**severity:** s3

**Priority:** p2

**Execution steps:**
Go to http://localhost:3000/analyze
click on "Text" button on home page
Upload text file 
Select all text and write something 

**Expected result:**
When text is selected and new text is written the file should automatically remove 

**Actual result:**
The is not deleted or removing automatically

**Picture:**
![Screenshot from 2024-05-13 14-32-02](https://github.com/xiarahman/eda-ai/assets/109179391/1d857b6b-652b-46f4-a928-5010ff921712)

**Comment by xrasad** [comment]
@shandev18 @Tehreem-personal please verify the issue

**Comment by Tehreem-personal** [comment]
I have Fixed this issue  in latest code. Please re-test

**Comment by xrasad** [comment]
issue is fixed
