### ISSUE TITLE
Uploaded text file once deleted then if you write something the deleted file reappeares.

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#67]
**Description:**
In the text module once uploaded text file is removed or deleted and again you write something in the dialog box the deleted file displayed automatically  

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to http://localhost:3000/analyze
click on "Text" Module on analyze page
Upload file

**Expected result:**
The system should not display deleted file 

**Actual result:**
The system display deleted file once it is deleted after witting some thing.

**Picture:**
![Screenshot from 2024-05-13 15-47-09](https://github.com/xiarahman/eda-ai/assets/109179391/402ec009-c5ad-407b-9935-ce34bdef5509)

**Comment by Tehreem-personal** [comment]
I have fixed this issue in latest code

**Comment by xrasad** [comment]
in which branch

**Comment by xrasad** [comment]
issue fixed
