### ISSUE TITLE
"It's suggestion" please do mention also supported file message over dialog box for user conveniance 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#68]
Description:
when you observe upload video module there is no supported video format message display 
severity: s3

Priority: p1

Execution steps:
Go to http://localhost:3000/analyze

Expected result:
The system should display supported file message also 
Actual result:
The system did not display supported file message

Picture:
![Screenshot from 2024-05-14 11-05-58](https://github.com/xiarahman/eda-ai/assets/109179391/e0530e1f-7eb8-4b3e-bd1e-b91c1cd7c910)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
waiting for some suggestions from UI team @devarsalanali

**Comment by devarsalanali** [comment]
Hey @shandev18, let's discuss it

**Comment by shandev18** [comment]
@xrasad issue fixed

**Comment by xrasad** [comment]
thanks issue is fixed
