### ISSUE TITLE
"its suggestion" please make sure that when user upload video "All files" do not show 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#69]
Description:
when you upload video there dialog box pop and when you observe in the below right side "All file" by default exist. I want to change it over only supported file 
severity: s3

Priority: p1

Execution steps:
Go to (http://localhost:3000/analyze)
Upload video

Expected result:
The system should not display all files 

Actual result:
The system display all files due to which some times wrong video format upload and might annoying for user  

Picture:
![Screenshot from 2024-05-14 11-25-32](https://github.com/xiarahman/eda-ai/assets/109179391/dcc135ab-83f4-4482-a90d-b2b6e8ea211d)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
thanks issue is fixed
