### ISSUE TITLE
System display enable 'Submit' Button for an Empty Requests"

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#7]
**Description:**
The system incorrectly displays the 'Submit' button as enabled even when the request form is empty. This is erroneous behavior, as the button should remain disabled until the user provides the necessary information in the request form. Thus, the system should be updated to ensure that the 'Submit' button is disabled for empty requests, prompting users to fill out the required fields before proceeding.

**severity:** 3

**Priority**: 1

**Execution steps:**
Go to eae web application
click on "try now" button
click on "Tr Text" button

**Expected result:**
The system should display disable submit button

**Actual result:**
The system displayed enable button

**Picture:**
![Screenshot from 2024-03-05 14-25-48](https://github.com/xiarahman/eda-ai/assets/109179391/d7df7eb5-c769-42ae-bff1-3a00243c2793)

**Comment by xrasad** [comment]
@Tehreem-personal could you please check the issue, thanks

**Comment by Tehreem-personal** [comment]
Fixed in latest code

**Comment by Tehreem-personal** [comment]
Fixed in latest code

**Comment by xrasad** [comment]
@Tehreem-personal thank you for resolving the issue.
