### ISSUE TITLE
Handle invalid video format from FrontEnd 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#70]
Description:
when you upload invalid video format the error message not display until video is proccessed from backend and it is time consuming please handle it from frontend and display proper easy to understand error message before backend proccess

severity: s1

Priority: p1

Execution steps:
Go to http://localhost:3000/analyze
Drag or upload video

Expected result:
The system should handle it from FE 

Actual result:
The system display error message when backend will complete its proccess

Picture:
![Screenshot from 2024-05-14 11-33-29](https://github.com/xiarahman/eda-ai/assets/109179391/6d7cad8e-6647-4ee4-b541-fe6a44578475)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
We now display the supported formats on the uploader and have fixed all format issues. This ensures that only supported files are shown to the user in the dialog box, reducing the likelihood of error messages. As a result, there is no need to update the UI to show error messages, as discussed with the UI and frontend teams.

**Comment by xrasad** [comment]
thanks issue is fixed
