### ISSUE TITLE
in video, Live stream module absent of "back" button and on 100% browser resolution sizes of preview and results carts are smaller

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#72]
**Description:**
Back button is missing in video and live stream module and also make sure buttons are aligned 

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
Drag or upload video

**Expected result:**
Back button should be present according to Figma Design and should be aligned 

**Actual result:**
button is missing 

**Picture:**
![Screenshot from 2024-05-15 10-04-38](https://github.com/xiarahman/eda-ai/assets/109179391/6d828e20-5fdb-425b-84c1-c69289dadd57)
![Screenshot from 2024-05-15 10-20-55](https://github.com/xiarahman/eda-ai/assets/109179391/6ea0ac94-082b-486b-b293-1d24bace622a)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by xrasad** [comment]
before resolving this issue kindly contact me thanks.

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
thanks issue is fixed
