### ISSUE TITLE
Content lenth of Text module should be 9999

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#74]
**Description:**
The length of text module is handled from back end and it is 9999 words if words are greater than 9999 it should display proper understandable error message 

**severity:** s3

**Priority:** p1

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
upload text

**Expected result:**
The system should display proper error message like "Sorry, the text module cannot exceed 9999 words. Please shorten your text and try again" 

**Actual result:**
The system did not display any error message

**Comment by xrasad** [comment]
@Tehreem-personal kindly verify the issue

**Comment by Tehreem-personal** [comment]
I have fixed this in latest code

**Comment by xrasad** [comment]
issue is fixed
