### ISSUE TITLE
invalid feature content on home page 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#75]
Description:
on home page feature carts content is invalid kindly correct it with proper content 
severity: s3

Priority: p1

Execution steps:
Go to http://localhost:3000
Go to feature section on home page 

Expected result:
The system should display proper content 

Actual result:
Invalid text/content is displayed 

Picture:
![Screenshot from 2024-05-16 12-53-22](https://github.com/xiarahman/eda-ai/assets/109179391/fad14d96-d1bf-4cf3-85e1-d95801dea46d)

**Comment by xrasad** [comment]
@Tehreem-personal please verify the issue and also features cart are more stretched horizontally kindly before tacking action compare it with figma

**Comment by Tehreem-personal** [comment]
fixed in latest code. Please take latest pull of my branch eda_4.

**Comment by xrasad** [comment]
issue if fixed thanks

**Comment by xrasad** [comment]
@Tehreem-personal @shandev18 please verify the issue

**Comment by shandev18** [comment]
content is changed already
![image](https://github.com/xiarahman/eda-ai/assets/133768718/432ee8f2-f6e9-48c3-9797-806f641a4987)
