### ISSUE TITLE
some text is visible with home screen on home page  when you click on home button or logo

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#78]
**Description:**
when you click on home button or logo Some text is visible with home screen

**severity:** s3

**Priority:** p2

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
Click on home button

**Expected result:**
The system should display only home screen when you click on home button or logo

**Actual result:**
The system did not display proper home screen

**Screenshot:**
![Screenshot from 2024-05-20 09-57-04](https://github.com/xiarahman/eda-ai/assets/109179391/2f65af35-0bfe-47c1-87f1-c96434f88f31)

**Comment by xrasad** [comment]
@Tehreem-personal please verify the issue

**Comment by Tehreem-personal** [comment]
fixed
