### ISSUE TITLE
invalid space is given to features carts on home page 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#79]
**Description:**
when you click on Features button the space from top and bottom are not same 

**severity:** s3

**Priority:** p2

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
Click on Features button

**Expected result:**
The system should display features cart with proper space from top to bottom

**Actual result:**
The top and bottom space not same

**Screenshot:**
![Screenshot from 2024-05-20 09-57-36](https://github.com/xiarahman/eda-ai/assets/109179391/b1cff102-ce8e-4629-8fc8-05fdb8701309)

**Comment by xrasad** [comment]
@Tehreem-personal please verify the issue

**Comment by Tehreem-personal** [comment]
fixed in latest code

**Comment by xrasad** [comment]
@Tehreem-personal please verify the issue

**Comment by xrasad** [comment]
please verify the issue
