### ISSUE TITLE
others and some emotions color are same and it should not be same 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#80]
**Description:**
when you upload video or text or even start live stream some emotion and other have same color on result page 

**severity:** s3

**Priority:** p1

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
Upload video or text 

**Expected result:**
The system should display different colors for each and every emotion

**Actual result:**
The system displayed same colors for multiples emotion and also for others

**Comment by xrasad** [comment]
@shandev18 @devarsalanali  please verify the issue

**Comment by devarsalanali** [comment]
Noted, @xrasad . I'll sort out this issue with the FE team.

**Comment by shandev18** [comment]
issue fixed in EDA-80

**Comment by xrasad** [comment]
Dictionary is disabled from BE and its implemented only on text module so kindly aligned the emotion and sentiment text also give different color to each emotion

**Comment by xrasad** [comment]
issue fixed and deployed on server
