### ISSUE TITLE
emoji (symbols)  emotion and sentiment text  are not aligned on sentences 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#83]
Description:
when you upload video/text the symbols emotion and sentiment text  are not aligned on sentence over both video and text module 

severity: s3

Priority: p1

Execution steps:
Go to http://localhost:3000/
click on "try now" button on home page
upload video or text 

Expected result:
The  emotion and sentiment text should be aligned 

Actual result:
The  emotion and sentiment text are not aligned 

Screenshot:
![Screenshot from 2024-05-20 12-21-24](https://github.com/xiarahman/eda-ai/assets/109179391/8b8d0282-41c5-4e54-a3c0-a76e3cd6f879)

**Comment by xrasad** [comment]
@Tehreem-personal did you fix this issue

**Comment by Tehreem-personal** [comment]
yes it is fixed in latest code.

**Comment by xrasad** [comment]
issue fixed
