### ISSUE TITLE
Button on sentiment cart should be sticky 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#88]
Description:
when some sentiment absent the button will move upward and downward according to the space on cart i have a suggestion that it should be sticky at appropriate place 

severity: s2

Priority: p1

Execution steps:
Go to http://localhost:3000/
click on "try now" button on home page
Upload video 

Expected result:
The button should be sticky

Actual result:
The button is not sticky

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
fixed this issue 
EDA-88

**Comment by xrasad** [comment]
issue is fixed thanks
