### ISSUE TITLE
System Fails to Clear Text in Dialog Box Upon File Deletion

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#9]
**Description:**
Despite file deletion, the system neglects to remove the associated text from the dialog box. This oversight results in misleading information persisting within the dialog, potentially confusing users. To ensure accurate feedback and enhance user experience, the system should promptly update the dialog box to reflect the deletion status of the file, providing clear and up-to-date information to users.

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to eae web application
click on "try now" button
click on "Tr Text" button
upload the by click on upload button
Then delete the file 

**Expected result:**
The system should remove the text in dialog box  automatically
**Actual result:**
The system did not remove the text automatically

**Pictures:**
![Screenshot from 2024-03-05 15-08-13](https://github.com/xiarahman/eda-ai/assets/109179391/0ba1c724-970f-4243-bcfa-7e2c1fcda6e3)
![Screenshot from 2024-03-05 15-08-24](https://github.com/xiarahman/eda-ai/assets/109179391/b979f050-a304-4fba-b7d4-b12b4e1bff71)

**Comment by xrasad** [comment]
@Tehreem-personal could you please check the issue, thanks

**Comment by Tehreem-personal** [comment]
Fixed. System now removes the error as soon as the file is deleted.

**Comment by xrasad** [comment]
@Tehreem-personal thank you for resolving the issue.
