### ISSUE TITLE
Invalid error message displayed on web application while in API its different 

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#92]
**Description:**
I have uploaded video file which is a large file and server can't handle it and through 413 Request Entity Too large error message in API response while on FE invalid error message displayed as mention in the picture 

**severity:** s2

**Priority:** p1

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
Upload video

**Expected result:**
The error message should be according to actual error 

**Actual result:**
The server displayed invalid error message on FE

**Screenshot**
![Screenshot from 2024-05-23 14-38-10](https://github.com/xiarahman/eda-ai/assets/109179391/df4c5e37-2049-41a7-8cd9-495631eb4cfc)

**Comment by xrasad** [comment]
@shandev18 please verify the issue

**Comment by shandev18** [comment]
issue fixed

**Comment by xrasad** [comment]
issue is fixed thanks
