### ISSUE TITLE
Video file that is larger than 1 GB should display proper error message and handled from FE

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#93]
**Description:**
If a video size is larger than 1GB should be handled from UI and should display proper appropriate error message 
**severity:** s3

**Priority:** p1

**Execution steps:**
Go to http://localhost:3000/
click on "try now" button on home page
Upload video

**Expected result:**
The system should display proper error message 

**Actual result:**
It is not yet handled from UI

**Comment by xrasad** [comment]
@shandev18  please verify the issue

**Comment by shandev18** [comment]
issue fixed in EDA-93

**Comment by xrasad** [comment]
thanks issue resolved
