### ISSUE TITLE
Sentiments and pie chart content overflow on some browser scale

### ISSUE THREAD

**Issue by xrasad** [xiarahman/eda-ai#99]
Description:
when you navigate to text module result page on some scale some content overflow 

severity: s3

Priority: p2

Execution steps:
Go to http://localhost:3000/
click on "try now" button on home page
upload text

Expected result:
The page should be fully responsive 

Actual result:
some content overflow 

Screenshot:
![Screenshot from 2024-05-28 14-17-56](https://github.com/xiarahman/eda-ai/assets/109179391/592b28a1-604a-4112-a3a6-2dfcde184d7f)
![Screenshot from 2024-05-28 14-16-35](https://github.com/xiarahman/eda-ai/assets/109179391/2f05032e-deb8-4db4-9163-5f5597d01e50)

**Comment by Tehreem-personal** [comment]
Responsiveness issues is fixed

**Comment by xrasad** [comment]
issue is fixed thanks
